# Generated by Django 2.1.1 on 2019-11-03 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20191103_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'created_at')},
        ),
    ]
